"""Shared node and audit helpers used across multiple E2E test files.

Deprecated: prefer ``tests.e2e.helpers.resources.UniqueResourceFactory``
for new tests. It provides deterministic cleanup and uses shared settings.
"""

import time
import warnings
from uuid import uuid4

import httpx2 as httpx

from tests.e2e.settings import (
    DOCKER_HOST,
    SSH_HOST,
    SSH_PASSWORD,
    SSH_PORT,
    SSH_USERNAME,
)
from tests.types import UnvalidatedJsonObject

_NODE_PAYLOAD = {
    "name": "e2e-node",
    "host": "10.0.0.1",
    "port": 22,
    "connection_type": "ssh",
}


def _deprecation_warning(function_name: str) -> None:
    warnings.warn(
        f"{function_name} is deprecated; use UniqueResourceFactory instead",
        DeprecationWarning,
        stacklevel=3,
    )


def create_node(e2e_client: httpx.Client, **overrides: object) -> UnvalidatedJsonObject:
    """Create a basic node for tests."""
    _deprecation_warning("create_node")
    data = {**_NODE_PAYLOAD, **overrides}
    data.setdefault("name", f"e2e-node-{uuid4().hex[:8]}")
    resp = e2e_client.post("/api/v1/nodes/", json=data)
    assert resp.status_code == 201
    return resp.json()


def create_ssh_node(
    e2e_client: httpx.Client,
    *,
    name: str | None = None,
    host: str = SSH_HOST,
    port: int = SSH_PORT,
    **overrides: object,
) -> UnvalidatedJsonObject:
    """Create an SSH node connected to the test SSH server.

    Uses Docker compose service name "ssh-server" as host by default.
    For tests that need to connect via mapped ports, pass host/port explicitly.
    A unique name is generated by default to avoid UNIQUE constraint conflicts
    across tests running against the same database.
    """
    _deprecation_warning("create_ssh_node")
    data: dict[str, object] = {
        "name": name or f"ssh-node-{uuid4().hex[:8]}",
        "host": host,
        "port": port,
        "connection_type": "ssh",
        "username": SSH_USERNAME,
        "password": SSH_PASSWORD,
    }
    data.update(overrides)
    resp = e2e_client.post("/api/v1/nodes/", json=data)
    assert resp.status_code == 201
    return resp.json()


def create_docker_node(
    e2e_client: httpx.Client,
    *,
    name: str | None = None,
    **overrides: object,
) -> UnvalidatedJsonObject:
    """Create a Docker node pointing to the internal DinD service."""
    _deprecation_warning("create_docker_node")
    data: dict[str, object] = {
        "name": name or f"docker-node-{uuid4().hex[:8]}",
        "host": SSH_HOST,
        "port": SSH_PORT,
        "connection_type": "docker",
        "username": SSH_USERNAME,
        "password": SSH_PASSWORD,
        "docker_host": DOCKER_HOST,
    }
    data.update(overrides)
    resp = e2e_client.post("/api/v1/nodes/", json=data)
    assert resp.status_code == 201
    return resp.json()


def wait_for_audit(
    client: httpx.Client,
    *,
    query: str = "",
    action: str | None = None,
    node_id: str | None = None,
    minimum_total: int = 1,
    timeout: float = 10.0,
) -> UnvalidatedJsonObject:
    """Poll the eventually-consistent transactional outbox.

    Never filters by *action* server-side — fetches all records (optionally
    scoped to *node_id*) and checks *action* locally so ``data["total"]``
    reflects the full count the caller expects.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        params: dict[str, str | int] = {"page": 1, "size": 100}
        if node_id:
            params["node_id"] = node_id
        if query:
            response = client.get(f"/api/v1/audit/{query}", params=params)
        else:
            response = client.get("/api/v1/audit/", params=params)
        assert response.status_code == 200
        data = response.json()
        if data["total"] >= minimum_total:
            items = data["items"]
            if action is None or any(i["action"] == action for i in items):
                return data
        time.sleep(0.2)
    raise AssertionError(
        f"audit event was not delivered: action={action}, query={query}"
    )
